"project_id_env": "CROWDIN_OPEN_PROJECT_ID"
"api_token_env": "CROWDIN_API_SECRET"
"pull_request_title": "chore(l10n): Translations updates"
"preserve_hierarchy": true
"files": [
  {
    "source": "/languages/pressbooks-book.pot",
    "dest": "/languages/pressbooks-book.pot",
    "translation": "/languages/%locale_with_underscore%.po",
    "languages_mapping": {
      "locale_with_underscore": {
        "bg": "bg_BG",
        "de": "de_DE",
        "en-GB": "en_GB",
        "es-ES": "es_ES",
        "es-CR": "es_CR",
        "fr": "fr_FR",
        "gl": "gl_ES",
        "hr": "hr",
        "it": "it_IT",
        "ja": "ja",
        "ka": "ka_GE",
        "kn": "kn",
        "lv": "lv",
        "nb": "nb_NO",
        "nl": "nl_NL",
        "pl": "pl",
        "pt-BR": "pt_BR",
        "ru": "ru_RU",
        "ta": "ta_LK",
        "tr": "tr_TR",
        "zh-CN": "zh"
      }
    }
  }
]
