sudo: required
language: php
addons:
  chrome: stable
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: cQLwFAhdJJszc5Eeghd6So0kaDBEzPzE3cpVENaFxPqViQIyrqg7fxqP7h9wvl7qEJrotjbos79w4nSf6Hn7BqLHXJ8wpqbYz3jXgnZhSetXPxUWuDFvEQD7Ylknop13kxvjkBjEs/Vce8hCv/tymM4TG4+DHQt/joYMPGnNVX4Aqkb4w6g6sZvCpzZOh61Uq+ALkgjYADVzgvZZYzXZDqLwiq20tXSLVVZA7o/E2/eMn+v/Uu5UHLVADFMFKCcB43JX0zgUHlF9iDvWUgAxbarWdRLh0BpNEKaoRdsnLWxrdCRQ0GZgGnlgmEiZWFrNfJLVg5OT9wdLF4q2qeZ7Ygci4+GrYoec6gpHJuU09D/2p+Zxh9LVcDKK9RcpNzLk0iiZ9aAFnuFMgnQJZylbedE1M1hkgwWSsD1nZp3lKAb7X+Pg9nKNsPwv4v8g57vjXWx4vyg8LWI0BX4WFMETBC+5HV0+9rG/+YFi/9HvQONkzO8Zh7zmfDOmYw55tr1SjCEYjWqVQGkoKOSbgSELmElWc4y9syw7FrixaaNJlPgDjf3jTthA+xGRb1WHmWrJ2JzxqmoaoAdVCUpVcIjZtH/4BjDLgVhmLNlCuLpjBMVHuy4yNcTaNH4rTmu9tpj3FND4/cPyA6/jFhCM8g5X0alNtpowczuRXW4vrNyHyC0=
branches:
  only:
  - dev
php:
- 7.1
env:
- TRAVIS_NODE_VERSION="8"
matrix:
  fast_finish: true
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install -g yarn
- yarn
- composer install
script:
- yarn run test
