name: Crowdin Translations Sync

on:
  push:
    branches:
      - translation-workflow-test
    paths:
      - 'languages/pressbooks-book.pot'

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        type: choice
        options:
          - download
          - seed
        default: download

jobs:
  upload-sources:
    if: github.event_name == 'push'
    uses: pressbooks/reusable-workflows/.github/workflows/crowdin.yml@crowdin
    with:
      action: upload
      pot_file_path: languages/pressbooks-book.pot
      crowdin_branch_name: pressbooks-book
      base_branch: translation-workflow-test
    secrets: inherit

  download-translations:
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'download')
    uses: pressbooks/reusable-workflows/.github/workflows/crowdin.yml@crowdin
    with:
      action: download
      pot_file_path: languages/pressbooks-book.pot
      languages_dir: languages/
      crowdin_branch_name: pressbooks-book
      base_branch: translation-workflow-test
    secrets: inherit

  seed-translations:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'seed'
    uses: pressbooks/reusable-workflows/.github/workflows/crowdin.yml@crowdin
    with:
      action: seed
      pot_file_path: languages/pressbooks-book.pot
      languages_dir: languages/
      crowdin_branch_name: pressbooks-book
      base_branch: translation-workflow-test
    secrets: inherit
