name: Npm build ⚙️

on:
  pull_request:
    branches: [ dev ]

jobs:
  update-npm-build:
    uses: pressbooks/reusable-workflows/.github/workflows/npm-build.yml@main
    secrets:
      PAT_FOR_GITHUB_ACTIONS: ${{ secrets.PAT_FOR_GITHUB_ACTIONS }}
