name: Update POT file 🌐

on:
  push:
    branches: [dev]
    paths:
      - "**/*.php"
      - "**/*.js"
  workflow_dispatch:

jobs:
  update-pot-file:
    uses: pressbooks/reusable-workflows/.github/workflows/update-pot.yml@main
    secrets: inherit
    with:
      domain: 'pressbooks-book'
      slug: 'pressbooks-book'
      package_name: 'McLuhan'
      headers: '{"Report-Msgid-Bugs-To": "https://github.com/pressbooks/pressbooks-book/issues"}'
